INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Manchester City','City','skyblue','white',1,1800000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Chelsea','Blues','mediumblue','darkblue',1,1080000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Tottenham Hotspur','Yiddos','white','midnightblue',1,1440000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Arsenal','Filth','red','white',1,1440000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Liverpool','Reds','red','darkred',1,1800000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Leicester','Foxes','royalblue','white',1,1080000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Wolves','Wolves','orange','black',1,1080000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Manchester United','United','red','black',1,1800000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Newcastle','Magpies','white','black',2,720000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Leeds United','Peacocks','yellow','blue',2,540000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Blackburn Rovers','Rovers','lightblue','white',2,540000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Derby County','Rams','whitesmoke','darkslategray',2,540000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Bristol City','Robins','darkred','snow',2,360000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Swansea City','Swans','gold','midnightblue',2,360000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Reading','Royals','dodgerblue','azure',2,720000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Middlesborough','Boro','firebrick','mistyrose',2,360000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Shrewsbury Town','Shrews','royalblue','gold',3,180000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Sunderland','Black Cats','crimson','black',3,288000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Ipswich Town','Tractor Boys','mediumblue','white',3,180000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Darlington','Quakers','darkgray','darkslategray',3,108000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Blackpool','Seasiders','darkorange','white',3,288000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Portsmouth','Pompey','darkmagenta','purple',3,288000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Crewe Alexandra','Railwaymen','gold','orange',3,108000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Bolton Wanderers','Trotters','yellow','darkslategray',3,180000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Exeter City','Grecians','darkslategray','darkred',3,180000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Fleetwood Town','Cod Army','khaki','darkblueslate',3,288000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Hull City','Tigers','orange','darkslategray',3,288000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Bristol Rovers','Gasheads','turqouise','darkcyan',3,180000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Port Vale','Valiants','yellow','white',3,108000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Charlton Athletic','Addicks','aqua','midnightblue',3,180000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Plymouth Argyle','Pilgrims','seagreen','white',3,108000);
INSERT INTO teams(name,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Doncaster Rovers','Vikings','crimson','dimgray',3,288000);
