INSERT INTO teams(name,division_id,gate) VALUES ('Manchester City',1,15000);
INSERT INTO teams(name,division_id,gate) VALUES ('Leeds United',1,9000);
INSERT INTO teams(name,division_id,gate) VALUES ('Tottenham Hotspur',1,12000);
INSERT INTO teams(name,division_id,gate) VALUES ('Arsenal',1,12000);
INSERT INTO teams(name,division_id,gate) VALUES ('Liverpool',1,15000);
INSERT INTO teams(name,division_id,gate) VALUES ('West Bromwich Albion',1,9000);
INSERT INTO teams(name,division_id,gate) VALUES ('Wolves',1,9000);
INSERT INTO teams(name,division_id,gate) VALUES ('Manchester United',1,15000);
INSERT INTO teams(name,division_id,gate) VALUES ('Newcastle',2,6000);
INSERT INTO teams(name,division_id,gate) VALUES ('Notts County',2,4500);
INSERT INTO teams(name,division_id,gate) VALUES ('Watford',2,4500);
INSERT INTO teams(name,division_id,gate) VALUES ('West Ham',2,4500);
INSERT INTO teams(name,division_id,gate) VALUES ('Bristol City',2,3000);
INSERT INTO teams(name,division_id,gate) VALUES ('Wrexham',2,3000);
INSERT INTO teams(name,division_id,gate) VALUES ('Chelsea',2,6000);
INSERT INTO teams(name,division_id,gate) VALUES ('Shrewsbury Town',2,3000);
INSERT INTO teams(name,division_id,gate) VALUES ('Port Vale',3,1500);
INSERT INTO teams(name,division_id,gate) VALUES ('Wimbledon',3,2400);
INSERT INTO teams(name,division_id,gate) VALUES ('Hereford',3,1500);
INSERT INTO teams(name,division_id,gate) VALUES ('Darlington',3,900);
INSERT INTO teams(name,division_id,gate) VALUES ('Blackpool',3,2400);
INSERT INTO teams(name,division_id,gate) VALUES ('Portsmouth',3,2400);
INSERT INTO teams(name,division_id,gate) VALUES ('Rochdale',3,900);
INSERT INTO teams(name,division_id,gate) VALUES ('Carlisle',3,1500);
INSERT INTO teams(name,division_id,gate) VALUES ('Exeter City',3,1500);
INSERT INTO teams(name,division_id,gate) VALUES ('Reading',3,2400);
INSERT INTO teams(name,division_id,gate) VALUES ('Hull City',3,2400);
INSERT INTO teams(name,division_id,gate) VALUES ('Barnsley',3,1500);
INSERT INTO teams(name,division_id,gate) VALUES ('Southend',3,900);
INSERT INTO teams(name,division_id,gate) VALUES ('Charlton Athletic',3,1500);
INSERT INTO teams(name,division_id,gate) VALUES ('Bournemouth',3,900);
INSERT INTO teams(name,division_id,gate) VALUES ('Fulham',3,2400);