INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Manchester City','Man City','City','skyblue','white',1,1800000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Chelsea','Chelsea','Blues','mediumblue','darkblue',1,1200000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Tottenham Hotspur','Tottenham','Yiddos','white','midnightblue',1,1200000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Arsenal','Arsenal','Filth','red','white',1,900000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Liverpool','Liverpool','Reds','red','darkred',1,1800000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Leicester','Leicester','Foxes','royalblue','white',1,900000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Wolves','Wolves','Wolves','orange','black',1,900000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Manchester United','Man United','United','red','black',1,1200000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Newcastle','Newcastle','Magpies','white','black',2,720000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Leeds United','Leeds','Peacocks','yellow','blue',2,540000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Blackburn Rovers','Blackburn','Rovers','lightblue','white',2,540000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Derby County','Derby','Rams','whitesmoke','darkslategray',2,540000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Bristol City','Bristol City','Robins','darkred','snow',2,360000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Swansea City','Swansea','Swans','gold','midnightblue',2,360000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Reading','Reading','Royals','dodgerblue','azure',2,720000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Middlesborough','Middlesboro','Boro','firebrick','mistyrose',2,360000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Shrewsbury Town','Shrewsbury','Shrews','royalblue','gold',3,180000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Sunderland','Sunderland','Black Cats','crimson','black',3,300000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Ipswich Town','Ipswich','Tractor Boys','mediumblue','white',3,180000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Darlington','Darlington','Quakers','darkgray','darkslategray',3,120000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Blackpool','Blackpool','Seasiders','darkorange','white',3,300000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Portsmouth','Portsmouth','Pompey','darkmagenta','purple',3,300000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Newport Town','Newport','Exiles','gold','orange',3,120000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Bolton Wanderers','Bolton','Trotters','yellow','darkslategray',3,180000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Exeter City','Exeter','Grecians','darkslategray','darkred',3,180000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Fleetwood Town','Fleetwood','Cod Army','khaki','darkblueslate',3,300000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Hull City','Hull City','Tigers','orange','darkslategray',3,300000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Bristol Rovers','Oxford','Yellows','yellow','darkcyan',3,180000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Port Vale','Port Vale','Valiants','yellow','white',3,120000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Charlton Athletic','Charlton','Addicks','aqua','midnightblue',3,180000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Plymouth Argyle','Plymouth','Pilgrims','seagreen','white',3,120000);
INSERT INTO teams(fullname,shortname,nickname,shirt_colour,shorts_colour,division_id,gate) VALUES ('Doncaster Rovers','Doncaster','Vikings','crimson','dimgray',3,300000);
